### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by ZFTurbo** [repertorium/SynthSOD-Baseline#1]
Hello. I have 2 questions. 
1) I tried to do inference and found out that for input `(300000, 2)` model returns output `(299008, 1)`. Does it mean that returned audio is mono?
2) Do you have some quality metrics for your pretrain models?

**Comment by DavidDiazGuerra** [comment]
Hello!

1. Yes, you're right. Actually, the model performs mono-to-mono separation since, even if the dataset contains stereo files, the model combines both channels at the very beginning and does not try to exploit the stereo information. It should be easy to modify the model to work with stereo signals tho.
2. In [our paper presenting the SynthSOD dataset](https://arxiv.org/abs/2409.10995) you can find the obtained signal-to-distortion ratios (SDR) for different datasets, I'm not sure if that's what you're looking for.
